export const category =[{
        name:"Islands",
        icon:require("../icons/island.jpg"),
    },{
        name:"National parks",
        icon:require("../icons/National_park.jpg"),
    },{
        name:"Amazing pools",
        icon:require("../icons/Pool.jpg"),
    },{
        name:"Amazing views",
        icon:require("../icons/Amazing_pools.jpg"),
    },{
        name:"Containers",
        icon:require("../icons/Container.jpg"),
    },{
        name:"Campers",
        icon:require("../icons/Campers.jpg")
    },{
        name:"OMG!",
        icon:require("../icons/OMG!.jpg"),
    },{
        name:"Beach",
        icon:require("../icons/Beach.jpg"),
    },{
        name:"Design",
        icon:require("../icons/Design.jpg")
    },{
        name:"Arctic",
        icon:require("../icons/Air_conditioning.jpg")
    },{
        name:"Tiny homes",
        icon:require("../icons/Tiny_home.jpg")
    },{
        name:"Caves",
        icon:require("../icons/Cave.png")
    },{
        name:"Camping",
        icon:require("../icons/Camping.jpg")
    },
    {
        name:"Cabins",
        icon:require("../icons/Cabin.jpg")
    },{
        name:"Treehouses",
        icon:require("../icons/Tree_house.png")
    },{
        name:"Surfing",
        icon:require("../icons/Surfing.jpg")
    },{
        name:"Bed & breakfasts",
        icon:require("../icons/Bed&breakfast.jpg")
    },
    {
        name:"Lakefront",
        icon:require("../icons/LakeFront.jpg")
    },{
        name:"Golfing",
        icon:require("../icons/Golf.jpg")
    },{
        name:"Trending",
        icon:require("../icons/Trending.jpg")
    },{
        name:"Tropical",
        icon:require("../icons/Tropical.jpg")
    },{
        name:"Rooms",
        icon:require("../icons/Room.jpg")
    },{
        name:"New",
        icon:require("../icons/New.jpg")
    },{
        name:"Iconic cities",
        icon:require("../icons/iconic.jpg")
    },{
        name:"Countryside",
        icon:require("../icons/CountrySide.jpg")
    },{
        name:"Mansions",
        icon:require("../icons/Mansion.jpg")
    },{
        name:"Farms",
        icon:require("../icons/Farm.jpg")
    },{
        name:"A-frames",
        icon:require("../icons/A-frames.jpg")
    },{
        name:"Earth homes",
        icon:require("../icons/EarthHomes.jpg")
    },{
        name:"Lake",
        icon:require("../icons/Lake.jpg")
    },{
        name:"Historical homes",
        icon:require("../icons/Historical.jpg")
    },{
        name:"Luxe",
        icon:require("../icons/Luxe.jpg")
    },{
        name:"Vineyards",
        icon:require("../icons/Vineyards.jpg")
    },{
        name:"Hanoks",
        icon:require("../icons/Hanoks.jpg")
    },{
        name:"Top of the world",
        icon:require("../icons/Top_of_the_world.jpg")
    },
    {
        name:"Skiing",
        icon:require("../icons/Skiing.jpg")
    },{
        name:"Cycladic homes",
        icon:require("../icons/Cycladic_home.jpg")
    },{
        name:"Castles",
        icon:require("../icons/Castle.jpg")
    },{
        name:"Chef's kitchens",
        icon:require("../icons/Chef's.jpg")
    },{
        name:"Beachfront",
        icon:require("../icons/Beachfront.jpg")
    },{
        name:"Shepherd's huts",
        icon:require("../icons/Shepher_hut.jpg")
    },{
        name:"Off-the-grid",
        icon:require("../icons/Off.jpg")
    },{
        name:"Ryokans",
        icon:require("../icons/Ryokans.jpg")
    },{
        name:"Play",
        icon:require("../icons/Play.jpg")
    },{
        name:"Minsus",
        icon:require("../icons/Minsu.jpg")
    },{
        name:"Windmills",
        icon:require("../icons/Windmill.jpg")
    },{
        name:"Casas particulares",
        icon:require("../icons/Casa_particular.jpg")
    },{
        name:"Towers",
        icon:require("../icons/Tower.jpg")
    },{
        name:"Domes",
        icon:require("../icons/Dome.jpg")
    },{
        name:"Desert",
        icon:require("../icons/Desert.jpg")
    },{
        name:"Barns",
        icon:require("../icons/Barn.jpg")
    },{
        name:"Yurts",
        icon:require("../icons/Yurt.jpg")
    },{
        name:"Ski-in/out",
        icon:require("../icons/Ski.jpg")
    },{
        name:"Houseboats",
        icon:require("../icons/Houseboat.jpg")
    },{
        name:"Boats",
        icon:require("../icons/Boats.jpg")
    },{
        name:"Adapted",
        icon:require("../icons/Adapted.jpg")
    },{
        name:"Creative spaces",
        icon:require("../icons/Creative.jpg")
    },{
        name:"Grand pianos",
        icon:require("../icons/Piano.jpg")
    },{
        name:"Riads",
        icon:require("../icons/Raid.jpg")
    },{
        name:"Trulli",
        icon:require("../icons/Trulli.jpg")
    },{
        name:"Dammusi",
        icon:require("../icons/Dammuso.jpg")
    }
]